---
- name: Deploy Maven Artifact
  hosts: localhost


  tasks:

    - name: Ensure deployment directory exists
      file:
        path: /home/admin1/deployment
        state: directory
        mode: '0755'

    - name: Copy artifact
      copy:
        src: /D:/CERTIFICATES/DevOps8/target/DevOps8-1.0-SNAPSHOT.jar
        dest: /home/admin1/deployment/DevOps8.jar
        remote_src: yes